package com.apratim.bookclub.javafx.design.controllers;

import javafx.event.ActionEvent;
import javafx.fxml.FXML;

public class EntryPointController {
	// Event Listener on Button.onAction
	@FXML
	public void enterClicked(ActionEvent event) {
		// TODO Autogenerated
	}
}
