# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: NjlhYTNiNTgyYTBiOGNhYjQ5NWZiZTJkNDQ3OTc5MTZkYWMwMmZmZGNlZWMyMDM5ZTY2OGI1OGE0MGU4NmUyYmNmMjk2NjUyOTQyODBmMmU5YjUxN2JjYjE2NmE5YWRkMjM2NDQ1YWM1NjMxNDU2YWEzZTJkOTJlNTJiODQ0YTQ=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
